Algoritmo "Area de um losangulo"
// Disciplina  : Lógica de Programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a área de um pentagono e exibe o resultado
// Autor(a)    : Diego de Carvalho Cabaleiro
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis
diametro1: Real
diametro2: real
resultado: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 escreva("Digite o valor da base do losangulo")
 leia(diametro1)
 escreva("Digite o valor da altura do losangulo")
 leia(diametro2)
 resultado<-diametro1*diametro2/2
 escreva("esta é a área do losangulo: ", resultado,"cm²")

Fimalgoritmo