Algoritmo "Area de um paralelogramo"
// Disciplina  : Lógica de Programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a área de um triângulo e exibe o resultado
// Autor(a)    : Diego de Carvalho Cabaleiro
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis
base: Real
altura: real
resultado: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 escreva("Digite o valor da base do paralelogramo")
 leia(base)
 escreva("Digite o valor da altura do paralelogramo")
 leia(altura)
 resultado<-base*altura
 escreva("esta é a área do paraleloramo: ", resultado,"cm²")

Fimalgoritmo