Algoritmo "Estrutura de Repeticao"
// Disciplina  : Linguagem e Lógica de Programação com visual G
// Professor   : Jailson Costa dos Santos 
// Descrição   : Exemplo de estrutura de repetição
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2026
Var
// Seção de Declarações das variáveis 
  conta:inteiro
  quant: inteiro
  oque: caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("O que você quer escrever: ")
  leia(oque)

  enquanto quant<10 faça
  escreval(oque)
  quant<- quant+1
  fimenquanto

Fimalgoritmo