Algoritmo "Identificacao de par ou impar"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Diego de Carvalho Cabaleiro
// Data atual  : 01/04/2026
Var
   // Seção de Declarações das variáveis
   numero1: real
   resultado: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o numero: ")
   leia(numero1)
   se numero1 mod 2 = 0 entao
      escreval ("esse numero é par")
   senao
      escreval ("esse numero é impar")
   fimse

Fimalgoritmo