Algoritmo "media de tres valores"
// Disciplina  : Lógica de Programação com visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Coleta e calcula a média de três valores
// Autor(a)    : Diego de Carvalho Cabaleiro
// Data atual  : 31/03/2026
Var
// Seção de Declarações das variáveis 
 valor1:real
 valor2:real
 valor3:real
 media:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite o valor1: ")
 leia(valor1)
 escreva("Digite o valor2: ")
 leia(valor2)
 escreva("Digite o valor3: ")
 leia(valor3)
 media<- (valor1+valor2+valor3)/3
 escreval(" ")
 escreva("Essa é a média: ", media)

Fimalgoritmo