Algoritmo "perimetro de retangulo"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Jailson Costa dos Santos
// Descrição   : Coleta e calcula o perimetro do retangulo em cm
// Autor(a)    : Diego de Carvalho Cabaleiro
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
 base: real
 altura: real
 resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  escreva("Digite o valor da base: ")
  leia(base)
  escreva("Digite o valor da altura: ")
  leia(altura)
  resultado<- 2*base+2*altura
  escreva("esse é o perímetro do retângulo: ", resultado,"cm")

Fimalgoritmo