Algoritmo "TrocaDosValores"
// Disciplina  : Linguagem e Lógica de Programação com Visual G
// Professor   : Jailson Costa dos Santos 
// Descrição   : Ler dois valores (inteiros, reais ou caracteres) para
// as variáveis A e B, e efetuar a troca dos valores de forma que a
// variável A passe a possuir o valor da variável B e a variável B
// passe a possuir o valor da variável A. Apresentar os valores trocados
// Autor(a)    : Diego de Carvalho Cabaleiro
// Data atual  : 11/04/2026
Var
// Seção de Declarações das variáveis 
A:caractere
B:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite algo para A: ")
leia(A)
escreva("Digite olgo para B: ")
leia(B)
escreval("Esse é A: ", B)
escreval("Esse é B: ", A)

Fimalgoritmo