Algoritmo "Validação de nota"
// Disciplina  : Lógica de Programação com visual G
// Professor   : Jailson Costa dos Santos 
// Descrição   : Valida se está aprovado ou reprovado com a referencia maior igual a 6 estara aprovado
// Autor(a)    : Diego de Carvalho Cabaleiro
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis 
valor:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("digite o valor: ")
  leia(valor)
  se valor>=6 entao
  escreva("Aprovado")
  senao
  escreva ("Reprovado")
  fimse

Fimalgoritmo